communitiesuk/funding-service-design-post-award-data-frontend

- .flaskenv
- config/envs/default.py
Previously placeholder values were being overwritten in `.flaskenv`, this created a difference in the deployed environment which doesn't read from this file 
e.g. 
placeholder values should no longer appear on deployed environment
> BAU: default config values

- app/templates/base.html
https://trello.com/c/wEHWANE1/433-front-end-add-sign-out-get-help-links
Adds a sign-out link inside the header, as according to the updated prototype
> Feature/ 433 sign out

- app/main/download_data.py
- app/main/forms.py
- app/templates/main/checkboxes.html
- app/templates/main/download.html
- app/templates/main/select.html
Previously we used duplicated form values and also the label attributes did not match the fields, this fixes those issues and adds the correct ITL codes for regions.
POST values should be meaningful e.g.
```
fund: high-streets
area: TLC
organisation: value1
outcome: value2
from-quarter: 1
from-year: 2022/2023
to-quarter: 2
to-year: 2023/2024
file_format: xlsx
download: y
```
Form inputs should select on clicking labels
> BAU: Fix form attributes

- app/main/data.py
- app/main/download_data.py
- app/main/routes.py
https://trello.com/c/OqTXa1L9/453-front-end-use-hardcoded-set-of-regions-instead-of-api-call
Use hardcoded region data instead of calling the API. 
> [#PAB-451] use hardcoded region data

- app/main/routes.py
- app/templates/main/data-glossary.html
- app/templates/main/download.html
Implements the HTML page, route at /data-glossary and link from /download to the funding glossary page
It should follow this design:
https://communitiesuk.github.io/funding-service-design-post-award-alpha/beta-central-repo/mvp-without-header-links/data-glossary.html
All the internal and external links should be working correctly
> add funding glossary html and routes

- app/__init__.py
- copilot/data-frontend/manifest.yml
Add Sentry integration to alert on exceptions, using existing functionality in utils library.
Have tested manually locally. Will not cause any changes locally unless you have `SENTRY_DSN` env var set.
> PAB-306: Add sentry integration

- .github/workflows/deploy.yml
Same change as https://github.com/communitiesuk/funding-service-design-post-award-data-store/pull/141 just for frontend
inject git sha env var
This is used by the app e.g. in the healthcheck and sentry reports to help us better track what version we are running on different environments
Have deployed on test, and sha currently viewable at: https://find-monitoring-data.test.gids.dev/healthcheck
> PAB-304: inject git sha env var

- app/templates/main/404.html
- app/templates/main/429.html
- app/templates/main/500.html
- app/templates/main/503.html
- app/templates/main/accessibility.html
- app/templates/main/cookies.html
- app/templates/main/data-glossary.html
- app/templates/main/download.html
- app/templates/main/privacy.html
[Trello Ticket](https://trello.com/c/hZdA2G24/374-p1-changes-to-the-breadcrumb-in-the-page-header)
Added back buttons to the UI of pages that would benafit from it
Download page back button directs to a page yet to be developed
Testing can be done manually
> 374: Added back button to each necessary page

- app/templates/main/download.html
The bottom border on the download page has been moved to below the final accordion in order to match design specifications in ticket https://trello.com/c/BhA3jVBT/509-changing-placement-of-bottom-border-of-final-filter
> [#PAB-509]: remove bottom border

- app/static/src/css/custom.css
- app/templates/main/checkboxes.html
Placed the dropdown checkboxes inside a scrollable frame as per ticket: https://trello.com/c/rcDW6WTF/508-adding-ability-to-scroll-in-filters
> [#PAB-508]: add scrollable checkboxes

- .pre-commit-config.yaml
Configures isort to use a configuration that doesn't conflict with black
> [BAU] use isort black profile to prevent pre-commit conflict

- copilot/data-frontend/manifest.yml
Adds basic auth to the frontend on test using a sidecar
Have deployed on test environment, credentials will be provided to the team separately.
> PAB-397: add basic auth sidecar on test environment

- app/main/download_data.py
- app/main/routes.py
- tests/test_routes.py
https://trello.com/c/dq3Y7Cgn/575-add-timestamp-to-data-extract-filename
These changes were originally made in the back-end repo, however there was some confusion as to where the filename is set. The content-disposition header is actually being set in both repos, however the file recieved by the user is overwritten by the headers in the front-end, which is why I chose to move this logic here. The plan is to revert the changes set in the data store repo to avoid repeated code, so downloading a file via the Swagger UI will revert to the previous data.extension pattern.
The file downloaded via the front-end UI should now read yyyy-mm-dd-hhmmss.format
> add current timestamp to file download

- Dockerfile
Increasing gunicorn worker timeout from 60 to 120 seconds in an attempt to prevent prod from crashing on download.
> [BAU_FIX] increase gunicorn worker timeout from 60 to 120

- Dockerfile
Increasing timeout further to maximum of 180 seconds.
Will re-test download after deployment. Increased to match increase in cloudfront timeout.
> FMD-46: Increase timeout to 180 seconds

- .github/workflows/deploy.yml
Bug fix after #66. Deploy failed as previous role did not have requisite permissions in the test account. Updates to use role with correct permissions.
Deploy should be successful post-merge
> FMD-38: update role name

- copilot/data-frontend/manifest.yml
In pre-prod environments requests were also being timed out by the default 60s timeout on NGINX. This increases it to match the Load Balancer and CDN timeouts.
Have deployed and tested on dev environment
> FMD-105: Increase NGINX proxy read timeout

- app/__init__.py
- config/envs/default.py
- config/envs/development.py
Previously app level logging was not enabled which meant that only server level gunicorn logs were outputted on the hosted environments.
This enables logging using the [existing logging functionality](https://github.com/communitiesuk/funding-service-design-utils?tab=readme-ov-file#logging) in utils
App should show app level logs when running locally
> BAU: enable app level logging

- config/envs/development.py
- requirements-dev.txt
- requirements.txt
- tests/conftest.py
Sister PR to: https://github.com/communitiesuk/funding-service-design-post-award-submit/pull/135
Overrides auth when running in development, using the existing override functionality in the `@login_required` decorator
When running locally, you should be able to access `/download` without going through Microsoft auth
> SMD-615: Debug user for local development

- copilot/data-frontend/manifest.yml
Sister PR to: https://github.com/communitiesuk/funding-service-design-post-award-submit/pull/144
Previously we had basic auth on test but not dev, this adds basic auth on dev.
Basic auth should be enabled on the dev environment
> BAU: add basic auth on dev

- app/templates/base.html
- app/templates/main/help.html
- app/templates/main/login.html
- config/envs/default.py
GOV.UK content style guide for emails says that email addresses should be lowercase:
https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style
> Fix contact email from config in templates

- app/main/routes.py
- app/templates/main/request-received.html
- tests/test_routes.py
FPASF-100
Created the download/email confirmation page according to our designs.
The details
We are tweaking the ‘download report’ journey so that users aren’t left on a page with no indication that work is happening while the report is being generated.
> Download/Email Confirmation Page

- app/main/download_data.py
- app/main/routes.py
- app/templates/main/download.html
- Update region filter on download page to call regions API and populate dropdown with regions that are used by projects in the database, rather than using pre-populated list of all regions regardless of whether or not we have projects for those regions
- Update naming from 'areas' to 'regions' for consistency
> FMD-241: Update frontend region filter

- app/main/routes.py
- scripts/extract_download_logs.py
- tests/test_logging.py
The download reporting mechanism was broken by the refactoring in: https://github.com/communitiesuk/funding-service-design-post-award-data-frontend/commit/025cf8f4844a72dba28c08fe3fe0a0888d642d18
This PR
* Restores the `request_type` key that was removed
* Makes the logs query backwards compatible so we can retrieve the logs using the refactored format
* Adds a unit test to make this interface harder to break in future
Script should return results for recent period e.g. `python3 ./scripts/extract_download_logs.py -e dev -m 1` (with dev AWS credentials.)
> FPASF-143: fix download report

- requirements-dev.txt
- requirements.txt
Pull in latest fsd_utils, so that we can use the latest version of sentry.
> Pull in latest fsd_utils and upgrade sentry

- .gitignore
- app/main/download_data.py
- app/main/routes.py
- tests/conftest.py
- tests/test_logging.py
- tests/test_routes.py
Ticket:
https://dluhcdigital.atlassian.net/browse/FPASF-103
Description:
Frontend changes for changing direct file download to a background task.
Comments:
- Does not include the two new routes for retrieving files
- Unit tests for testing direct download functionality have been commented out for now.
> frontend changes for async_download

- scripts/extract_download_logs.py
Since the `email_address` key was added as part of the async work this broke the `extract_download_logs` report as it expects all `fieldnames` to be explicitly defined.
This fixes it by removing `email_address` from the serialised fields if present.
Script should succeed e.g. ` python3 ./scripts/extract_download_logs.py -e dev -d 14 -f output.csv`
> BAU: Filter out email_address key as that was breaking reporting

- copilot/data-frontend/manifest.yml
Switch on maintenance mode for all envs
> FPASF-284: Switch on maintenance mode for all envs
