communitiesuk/funding-service-design-post-award-data-frontend

Dockerfile, app.py, app/__init__.py, run/gunicorn/run.py, wsgi.py
Adds a Dockerfile 
- [NA] Unit tests and other appropriate tests added or updated
- [NA] README and other documentation has been updated / added (if needed)
=> [BAU] add Dockerfile

.github/workflows/deploy.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
Add build assets step to deploy workflow
Styling should be visible on deployed frontend
=> PAB-237: add static build step

app/__init__.py, app/main/routes.py, tests/conftest.py, tests/test_routes.py
https://trello.com/c/uasRmVnS/329-test-authentication-on-aws-hosted-instance
Requires login for all requests to the application apart from Healthcheck
=> [#PAB-329] require login for all routes

.github/workflows/deploy.yml, copilot/data-frontend/manifest.yml
Update data store env var and remove defaulted values
Should deploy successfully
=> PAB-237: Update data store env var and remove defaulted values

app/templates/base.html
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
_A brief description of the pull request_
=> #PAB-359: removed cookie banner, redirected cookie link

copilot/data-frontend/manifest.yml
Add required env vars and secrets
Sign in should work after deployment
=> PAB-237: Secrets and env vars

app/const.py, app/main/data.py, app/main/routes.py, config/envs/unit_test.py, tests/conftest.py, tests/test_connections.py, tests/test_routes.py
https://trello.com/c/2nNVAwIx/366-add-file-download-server-side-functionality-to-front-end
Built out the download POST endpoint to return a file of the requested format.
=> [#PAB-366] add download post endpoint

app/templates/base.html
For security reasons we need to use the full logout route
Log Out link should do a full log-out
=> BAU: use full logout route

README.md
Spotted in the course of another story these steps were missing
Steps should work locally
=> BAU: add steps to install pre-commit

.github/workflows/deploy.yml, copilot/data-frontend/manifest.yml, copilot/environments/production/manifest.yml
Add production env manifest files
Will be testable once corresponding github actions pipeline has been added
=> PAB-400: Production env manifest

.github/workflows/deploy.yml
* Utilising a secret instead of hard-coded account number
* Using date and role name to provide a neat cloudtrail for access analytics
=> PAB-400 Updating deploy to utilise new account role

app/templates/main/download.html
Comments out the period filter from the download page whilst the mapping logic is still being developed.
=> [BAU_FIX] remove unfinished period filter from download page

Dockerfile
Increase gunicorn worker timeout from 30 to 60 seconds
=> [BAU_FIX] increase gunicorn worker timeout

app/main/download_data.py
Removes Custom -> Other outcome category change
=> [BAU_FIX] remove Custom -> Other outcome category option

app/main/routes.py, app/static/src/css/custom.css, app/templates/base.html, app/templates/main/data-glossary.html, app/templates/main/download.html, app/templates/main/help.html
https://trello.com/c/wEHWANE1/433-front-end-add-sign-out-get-help-links
Contains the HTML and custom CSS for the 'get help' page at /help, along with updating the appearance of the banner at /download to reflect the most recent design.
=> Get Help/Log Out

.flaskenv, app/__init__.py, app/main/routes.py, app/templates/main/login.html, tests/conftest.py, tests/test_routes.py
https://trello.com/c/86rsX4To/397-landing-page-for-sign-in
The landing page should look like this:
The styling should now be displayed correctly on our test URL
=> Sign-in page

.github/workflows/deploy.yml
Workaround for regression described in: https://github.com/aws/copilot-cli/issues/5265
Will re-deploy post-merge
=> BAU: pin to previous version of copilot

copilot/data-frontend/manifest.yml
Change alias to new URL
URL should update after deploy
=> FMD-38: update domain

.github/workflows/deploy.yml
add dev env and inject manifest values
Have tested by deploying branch to dev and test e.g.
https://github.com/communitiesuk/funding-service-design-post-award-data-frontend/actions/runs/6509098587/job/17679845820
=> FMD-37: add dev env and inject manifest values

app/main/routes.py, tests/test_routes.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FMD/boards/139?selectedIssue=FMD-149
Replica of Submit front end HTTP error handling changes - https://github.com/communitiesuk/funding-service-design-post-award-submit/pull/105
=> error handling for uncaught http errors

README.md
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140/backlog?selectedIssue=SMD-495
Updates setup instructions to make them more detailed and consistent with the data-store README
=> SMD-495 add detail to setup instructions

app/main/routes.py
Add authentication to /start endpoint
`/start` endpoint should force authentication
=> BAU: Add authentication to /start endpoint

.github/workflows/deploy.yml, copilot/data-frontend/manifest.yml
Following the rebuilding of the dev environment we no longer need these overrides in the Github Action as the environments are more consistent
Have deployed branch to dev environment
=> FMD-194: remove unneeded overrides

app/main/routes.py
We want to start logging download requests for analytical purposes.
Log line should be added before download is initiated.
=> FMD-232 add logging to download requests

scripts/extract_download_logs.py
Adds script to generate a report based on logging added in #88 
Can be ran by users with AWS access
=> FMD-232: Add script to extract download logs into reporting output

app/main/routes.py, scripts/extract_download_logs.py
Adds email to log and report output (so we can distinguish internal usage)
Report should include email address for subsequent queries
=> FMD-232: add email to log and report output

copilot/data-frontend/overrides/cfn.patches.yml
Increase log retention period (for reporting purposes. as per #88)
Will check following deployment
=> FMD-232: increase log retention to 90 days

requirements-dev.txt, requirements.in, requirements.txt, scripts/extract_download_logs.py
Adds option to email report using Notify
Also adds months time delta to support desired reporting period.
Should email report if `--email` is specified and `NOTIFY_API_KEY` is set.
=> FMD-232: email report option

copilot/download-report/manifest.yml, copilot/download-report/overrides/cfn.patches.yml, scripts/extract_download_logs.py
Runs report script on a monthly schedule 
(Also adds Sentry integration to alert on failures)
Have tested on dev environment
=> FMD-232: Run Download report as Scheduled Job

app/templates/main/request-received.html
Updating and fixing the page content, requirements from the design team.
=> Update page content

.pre-commit-config.yaml, app/templates/base.html, app/templates/main/404.html, app/templates/main/429.html, app/templates/main/500.html, app/templates/main/503.html, app/templates/main/accessibility.html, app/templates/main/cookies.html, app/templates/main/data-glossary.html, app/templates/main/download.html, app/templates/main/help.html, app/templates/main/login.html, app/templates/main/privacy.html, app/templates/main/request-received.html, app/templates/main/select.html
Ticket https://dluhcdigital.atlassian.net/browse/SMD-813
Re-enable djlint pre-commit and fix linting issues. 
Are tests passing?
=> [SMD-813] Re enable djlint precommit

app/main/download_data.py, app/main/forms.py, app/main/routes.py, app/static/src/css/custom.css, app/templates/main/file-not-found.html, app/templates/main/request-received.html, app/templates/main/retrieve-download.html, tests/test_download_data.py, tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/FPASF-153
Once user get an email with the link to download the file.
If file does not exist user will redirect to the 'File not found' page.
If file exist in S3 it will redirect to the download page having download button, once user click on the download button it will
create a Presigned url for the short time to download the file.
=> Send user to find service download page to download the file

app/__init__.py, app/templates/base.html, app/templates/main/maintenance-mode.html, config/envs/default.py
Adds a maintenance mode page to the app.
=> Add maintenance mode page

app/main/forms.py, app/main/routes.py, app/static/src/css/custom.css, app/templates/main/download.html, tests/test_routes.py
Update the content and change the dropdown to a radio question as per the prototype
=> updated find home page content

requirements-dev.txt, requirements.in, requirements.txt
Bump utils to pick up changes from https://github.com/communitiesuk/funding-service-design-utils/pull/150
Return path param should be included in no token URL
=> FPASF-376: bump utils

requirements-dev.txt, requirements.txt, tests/test_routes.py
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
bump utils to pick up changes
=> BAU: bump utils
